In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
df = pd.read_csv("../datasets/BaseDPEvolucaoMensalCisp.csv", sep=";", decimal=",", encoding="latin1")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37588 entries, 0 to 37587
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37588 non-null  int64
 1   mes                         37588 non-null  int64
 2   ano                         37588 non-null  int64
 3   mes_ano                     37588 non-null  object
 4   aisp                        37588 non-null  int64
 5   risp                        37588 non-null  int64
 6   munic                       37588 non-null  object
 7   mcirc                       37588 non-null  int64
 8   regiao                      37588 non-null  object
 9   hom_doloso                  37588 non-null  int64
 10  lesao_corp_morte            37588 non-null  int64
 11  latrocinio                  37588 non-null  int64
 12  cvli                        37588 non-null  int64
 13  hom_por_interv_policial     37588 non-null  int64
 14  feminicidio                 2466 non-null   float64
 15  letalidade_violenta         37588 non-null  int64
 16  tentat_hom                  37588 non-null  int64
 17  tentativa_feminicidio       2466 non-null   float64
 18  lesao_corp_dolosa           37588 non-null  int64
 19  estupro                     37588 non-null  int64
 20  hom_culposo                 37588 non-null  int64
 21  lesao_corp_culposa          37588 non-null  int64
 22  roubo_transeunte            37588 non-null  int64
 23  roubo_celular               37588 non-null  int64
 24  roubo_em_coletivo           37588 non-null  int64
 25  roubo_rua                   37588 non-null  int64
 26  roubo_veiculo               37588 non-null  int64
 27  roubo_carga                 37588 non-null  int64
 28  roubo_comercio              37588 non-null  int64
 29  roubo_residencia            37588 non-null  int64
 30  roubo_banco                 37588 non-null  int64
 31  roubo_cx_eletronico         37569 non-null  float64
 32  roubo_conducao_saque        37588 non-null  int64
 33  roubo_apos_saque            37588 non-null  int64
 34  roubo_bicicleta             20199 non-null  float64
 35  outros_roubos               37588 non-null  int64
 36  total_roubos                37588 non-null  int64
 37  furto_veiculos              37588 non-null  int64
 38  furto_transeunte            37588 non-null  int64
 39  furto_coletivo              37588 non-null  int64
 40  furto_celular               37588 non-null  int64
 41  furto_bicicleta             20199 non-null  float64
 42  outros_furtos               37588 non-null  int64
 43  total_furtos                37588 non-null  int64
 44  sequestro                   37588 non-null  int64
 45  extorsao                    37588 non-null  int64
 46  sequestro_relampago         37588 non-null  int64
 47  estelionato                 37588 non-null  int64
 48  apreensao_drogas            37588 non-null  int64
 49  posse_drogas                32942 non-null  float64
 50  trafico_drogas              32942 non-null  float64
 51  apreensao_drogas_sem_autor  32942 non-null  float64
 52  recuperacao_veiculos        37588 non-null  int64
 53  apf                         32942 non-null  float64
 54  aaapai                      32942 non-null  float64
 55  cmp                         32942 non-null  float64
 56  cmba                        32942 non-null  float64
 57  ameaca                      37588 non-null  int64
 58  pessoas_desaparecidas       37588 non-null  int64
 59  encontro_cadaver            37588 non-null  int64
 60  encontro_ossada             37588 non-null  int64
 61  pol_militares_mortos_serv   37588 non-null  int64
 62  pol_civis_mortos_serv       37588 non-null  int64
 63  registro_ocorrencias        37588 non-null  int64
 64  fase                        37588 non-null  int64
dtypes: float64(12), int64(50), object(3)
memory usage: 18.6+ MB

In [2]:
print(df["regiao"].unique())

['Capital' 'Baixada Fluminense' 'Interior'
 'Grande NiterÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â³i' 'Grande Niterói']

In [3]:
df = df[ df["regiao"].isin(["Capital", "Baixada Fluminense"])]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16472 entries, 0 to 37510
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        16472 non-null  int64
 1   mes                         16472 non-null  int64
 2   ano                         16472 non-null  int64
 3   mes_ano                     16472 non-null  object
 4   aisp                        16472 non-null  int64
 5   risp                        16472 non-null  int64
 6   munic                       16472 non-null  object
 7   mcirc                       16472 non-null  int64
 8   regiao                      16472 non-null  object
 9   hom_doloso                  16472 non-null  int64
 10  lesao_corp_morte            16472 non-null  int64
 11  latrocinio                  16472 non-null  int64
 12  cvli                        16472 non-null  int64
 13  hom_por_interv_policial     16472 non-null  int64
 14  feminicidio                 1080 non-null   float64
 15  letalidade_violenta         16472 non-null  int64
 16  tentat_hom                  16472 non-null  int64
 17  tentativa_feminicidio       1080 non-null   float64
 18  lesao_corp_dolosa           16472 non-null  int64
 19  estupro                     16472 non-null  int64
 20  hom_culposo                 16472 non-null  int64
 21  lesao_corp_culposa          16472 non-null  int64
 22  roubo_transeunte            16472 non-null  int64
 23  roubo_celular               16472 non-null  int64
 24  roubo_em_coletivo           16472 non-null  int64
 25  roubo_rua                   16472 non-null  int64
 26  roubo_veiculo               16472 non-null  int64
 27  roubo_carga                 16472 non-null  int64
 28  roubo_comercio              16472 non-null  int64
 29  roubo_residencia            16472 non-null  int64
 30  roubo_banco                 16472 non-null  int64
 31  roubo_cx_eletronico         16453 non-null  float64
 32  roubo_conducao_saque        16472 non-null  int64
 33  roubo_apos_saque            16472 non-null  int64
 34  roubo_bicicleta             8880 non-null   float64
 35  outros_roubos               16472 non-null  int64
 36  total_roubos                16472 non-null  int64
 37  furto_veiculos              16472 non-null  int64
 38  furto_transeunte            16472 non-null  int64
 39  furto_coletivo              16472 non-null  int64
 40  furto_celular               16472 non-null  int64
 41  furto_bicicleta             8880 non-null   float64
 42  outros_furtos               16472 non-null  int64
 43  total_furtos                16472 non-null  int64
 44  sequestro                   16472 non-null  int64
 45  extorsao                    16472 non-null  int64
 46  sequestro_relampago         16472 non-null  int64
 47  estelionato                 16472 non-null  int64
 48  apreensao_drogas            16472 non-null  int64
 49  posse_drogas                14435 non-null  float64
 50  trafico_drogas              14435 non-null  float64
 51  apreensao_drogas_sem_autor  14435 non-null  float64
 52  recuperacao_veiculos        16472 non-null  int64
 53  apf                         14435 non-null  float64
 54  aaapai                      14435 non-null  float64
 55  cmp                         14435 non-null  float64
 56  cmba                        14435 non-null  float64
 57  ameaca                      16472 non-null  int64
 58  pessoas_desaparecidas       16472 non-null  int64
 59  encontro_cadaver            16472 non-null  int64
 60  encontro_ossada             16472 non-null  int64
 61  pol_militares_mortos_serv   16472 non-null  int64
 62  pol_civis_mortos_serv       16472 non-null  int64
 63  registro_ocorrencias        16472 non-null  int64
 64  fase                        16472 non-null  int64
dtypes: float64(12), int64(50), object(3)
memory usage: 8.3+ MB

In [4]:
df["risp"].value_counts()

risp
1    6905
3    5187
2    4371
5       6
6       3
Name: count, dtype: int64

In [5]:
df[ df["risp"]==6]

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
11,16,1,2003,2003m01,36,6,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,141,3,1,0,0,0,973,3
137,16,2,2003,2003m02,36,6,Rio de Janeiro,3304557,Capital,5,...,NaN,NaN,122,8,2,0,0,0,1015,3
263,16,3,2003,2003m03,36,6,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,132,5,4,0,0,0,1079,3

In [6]:
## esses dados estão com a risp sendo 6, porem a regiao capital e cisp 16 se referem a barra da tijuca, pertencente a risp 2. 
## como sao poucos dados, assumimos que se trata de um erro de preenchimento, e trocaamos para o valor correto

df.loc[:,"risp"] = df.loc[:,"risp"].replace(6,2)
df["risp"].value_counts()

risp
1    6905
3    5187
2    4374
5       6
Name: count, dtype: int64

In [7]:
df[ df["risp"]==5]

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
53,65,1,2003,2003m01,34,5,Magé;Guapimirim,9999982,Baixada Fluminense,4,...,NaN,NaN,70,4,0,0,0,0,285,3
54,66,1,2003,2003m01,34,5,Magé,3302502,Baixada Fluminense,8,...,NaN,NaN,53,4,4,0,0,0,278,3
179,65,2,2003,2003m02,34,5,Magé;Guapimirim,9999982,Baixada Fluminense,5,...,NaN,NaN,85,3,3,0,0,0,313,3
180,66,2,2003,2003m02,34,5,Magé,3302502,Baixada Fluminense,11,...,NaN,NaN,61,4,0,0,0,0,245,3
305,65,3,2003,2003m03,34,5,Magé;Guapimirim,9999982,Baixada Fluminense,4,...,NaN,NaN,98,1,2,0,0,0,326,3
306,66,3,2003,2003m03,34,5,Magé,3302502,Baixada Fluminense,8,...,NaN,NaN,63,9,5,0,0,0,247,3

In [8]:
# mesma logica da anterior, porém aqui a risp correta é 3
df.loc[:,"risp"] = df.loc[:,"risp"].replace(5,3)
df["risp"].value_counts()

risp
1    6905
3    5193
2    4374
Name: count, dtype: int64

In [9]:
df["mes_ano"] = pd.to_datetime(
    df.loc[:,'mes_ano'].str.replace('m', '-', regex=False),
    format='%Y-%m'
)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16472 entries, 0 to 37510
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        16472 non-null  int64
 1   mes                         16472 non-null  int64
 2   ano                         16472 non-null  int64
 3   mes_ano                     16472 non-null  datetime64[ns]
 4   aisp                        16472 non-null  int64
 5   risp                        16472 non-null  int64
 6   munic                       16472 non-null  object
 7   mcirc                       16472 non-null  int64
 8   regiao                      16472 non-null  object
 9   hom_doloso                  16472 non-null  int64
 10  lesao_corp_morte            16472 non-null  int64
 11  latrocinio                  16472 non-null  int64
 12  cvli                        16472 non-null  int64
 13  hom_por_interv_policial     16472 non-null  int64
 14  feminicidio                 1080 non-null   float64
 15  letalidade_violenta         16472 non-null  int64
 16  tentat_hom                  16472 non-null  int64
 17  tentativa_feminicidio       1080 non-null   float64
 18  lesao_corp_dolosa           16472 non-null  int64
 19  estupro                     16472 non-null  int64
 20  hom_culposo                 16472 non-null  int64
 21  lesao_corp_culposa          16472 non-null  int64
 22  roubo_transeunte            16472 non-null  int64
 23  roubo_celular               16472 non-null  int64
 24  roubo_em_coletivo           16472 non-null  int64
 25  roubo_rua                   16472 non-null  int64
 26  roubo_veiculo               16472 non-null  int64
 27  roubo_carga                 16472 non-null  int64
 28  roubo_comercio              16472 non-null  int64
 29  roubo_residencia            16472 non-null  int64
 30  roubo_banco                 16472 non-null  int64
 31  roubo_cx_eletronico         16453 non-null  float64
 32  roubo_conducao_saque        16472 non-null  int64
 33  roubo_apos_saque            16472 non-null  int64
 34  roubo_bicicleta             8880 non-null   float64
 35  outros_roubos               16472 non-null  int64
 36  total_roubos                16472 non-null  int64
 37  furto_veiculos              16472 non-null  int64
 38  furto_transeunte            16472 non-null  int64
 39  furto_coletivo              16472 non-null  int64
 40  furto_celular               16472 non-null  int64
 41  furto_bicicleta             8880 non-null   float64
 42  outros_furtos               16472 non-null  int64
 43  total_furtos                16472 non-null  int64
 44  sequestro                   16472 non-null  int64
 45  extorsao                    16472 non-null  int64
 46  sequestro_relampago         16472 non-null  int64
 47  estelionato                 16472 non-null  int64
 48  apreensao_drogas            16472 non-null  int64
 49  posse_drogas                14435 non-null  float64
 50  trafico_drogas              14435 non-null  float64
 51  apreensao_drogas_sem_autor  14435 non-null  float64
 52  recuperacao_veiculos        16472 non-null  int64
 53  apf                         14435 non-null  float64
 54  aaapai                      14435 non-null  float64
 55  cmp                         14435 non-null  float64
 56  cmba                        14435 non-null  float64
 57  ameaca                      16472 non-null  int64
 58  pessoas_desaparecidas       16472 non-null  int64
 59  encontro_cadaver            16472 non-null  int64
 60  encontro_ossada             16472 non-null  int64
 61  pol_militares_mortos_serv   16472 non-null  int64
 62  pol_civis_mortos_serv       16472 non-null  int64
 63  registro_ocorrencias        16472 non-null  int64
 64  fase                        16472 non-null  int64
dtypes: datetime64[ns](1), float64(12), int64(50), object(2)
memory usage: 8.3+ MB

In [13]:
df = df[df["ano"] >=2014]

In [14]:
df.to_pickle('../datasets/dataframe.pkl')